# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d710f15308860804e2ac483c3deb989863916809977ad5a9c91d6d6f4a43239839b8481f1f87f839c725e6f9676a13cea0ad636c0282c4a42b6cebe4b6469db

test:
  secret_key_base: 39f3af2f2dc6ab14087fb2ab1b8b6a5811e12dd8a6d5ffeb4cf1cced7e449f94e52a461c1a1bed0373116de8807c0aa6c08d63473912cc124d89068a5984441b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
